### PR TITLE
Style modifications

### PR DESCRIPTION
**Pull request by Dev-Daniel-121**
Made some style modifications

### CODE REVIEW

**Comment by Dev-Daniel-121** [comment]
"I don't know what am I doing"
"I don't know what am I reading"

**Comment by Dev-Daniel-121** [comment]
Haahahahhahahahhahahahh

**Comment by Dev-Daniel-121** [comment]
Now I will create the "About Us" Section, edit some Images that are there, and finally build the "Home Page" for our projects.

**Comment by Dev-Samuel-121** [comment]
[Semanas.zip](https://github.com/user-attachments/files/17723864/Semanas.zip)

**Comment by Dev-Samuel-121** [comment]
Try this :)

**Comment by Dev-Daniel-121** [comment]
> [Semanas.zip](https://github.com/user-attachments/files/17723864/Semanas.zip)

---

It can't be real!!! 😲😨

You answer!!!!! Finaly !!!!! Can we finish the project!? I was woring alone 🙃

**Comment by Dev-Daniel-121** [comment]
[PT.zip](https://github.com/user-attachments/files/17756545/PT.zip)
# Já recebeu?

**Comment by Dev-Daniel-121** [comment]
# O arquivo já _**enviado**_

[PT.zip](https://github.com/user-attachments/files/17756547/PT.zip)

**Comment by Dev-Daniel-121** [comment]
[Ag-15.zip](https://github.com/user-attachments/files/17759640/Ag-15.zip)

**Comment by Dev-Daniel-121** [comment]
# RECEBA
---

[Ag-15.zip](https://github.com/user-attachments/files/17759642/Ag-15.zip)

**Pull request closed without merging**
